# Generated by Django 3.0.1 on 2019-12-27 16:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type_of_habit', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('type_of_goal', models.CharField(default='total', max_length=50)),
                ('goal_amount', models.FloatField()),
                ('current_completed_timed_amount', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('current_times_activity_done', models.IntegerField(blank=True, default=0, null=True)),
                ('completed', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('timed_total', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('count_times_done_total', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.Habit')),
            ],
        ),
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('daily_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.Daily_Habit')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.Habit')),
            ],
        ),
    ]
