# Generated by Django 2.2.7 on 2019-11-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20191119_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='total_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
