# Generated by Django 2.2.7 on 2019-11-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_auto_20191120_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
