# Generated by Django 2.2.7 on 2019-11-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_auto_20191121_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='type_of_goal',
            field=models.CharField(default='total', max_length=50),
        ),
    ]
