# Generated by Django 2.2.7 on 2019-11-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_type_of_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='current_completed_timed_amount',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='current_times_activity_done',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
