# Generated by Django 2.2.7 on 2019-11-23 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_auto_20191122_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='current_completed_timed_amount',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal_amount',
            field=models.FloatField(),
        ),
    ]
