# Generated by Django 2.2.7 on 2019-11-24 16:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_auto_20191123_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('timed_total', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('count_times_done_total', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.Habit')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='daily_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.Daily_Habit'),
        ),
    ]
