# Generated by Django 2.2.7 on 2019-11-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_auto_20191124_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_habit',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
